<?php
declare(strict_types=1);

namespace Kettari\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Kettari\TelegramBundle\Entity\Chat;
use Kettari\TelegramBundle\Entity\User;


/**
 * ChatMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatMemberRepository extends EntityRepository
{
  /**
   * Finds chat member by chat and user.
   *
   * @param \Kettari\TelegramBundle\Entity\Chat $chat
   * @param \Kettari\TelegramBundle\Entity\User $user
   * @return object|null
   */
  public function findOneByChatAndUser(Chat $chat, User $user)
  {
    return $this->findOneBy(['chat' => $chat, 'user' => $user]);
  }
}
