<?php

namespace Kaula\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends EntityRepository
{
  /**
   * Finds chat by telegram ID.
   *
   * @param float $telegramId
   * @return object|null
   */
  public function findOneByTelegramId($telegramId)
  {
    return $this->findOneBy(['telegram_id' => $telegramId], ['title' => 'ASC']);
  }
}
