<?php
declare(strict_types=1);

namespace Kettari\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * HookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HookRepository extends EntityRepository
{
  /**
   * Finds hooks by chat and user IDs.
   *
   * @param int $chatId
   * @param int $userId
   * @return array
   */
  public function findActive(int $chatId, int $userId)
  {
    return $this->findBy(
      [
        'chat' => $chatId,
        'user' => $userId,
      ]
    );
  }
}
