<?php
declare(strict_types=1);

namespace Kettari\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Kettari\TelegramBundle\Entity\Chat;
use Kettari\TelegramBundle\Entity\User;


/**
 * HookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HookRepository extends EntityRepository
{
  /**
   * Finds hooks by chat and user IDs.
   *
   * @param \Kettari\TelegramBundle\Entity\Chat $chat
   * @param \Kettari\TelegramBundle\Entity\User $user
   * @return array
   */
  public function findActive(Chat $chat, User $user)
  {
    return $this->findBy(
      [
        'chat' => $chat,
        'user' => $user,
      ]
    );
  }
}
