<?php
declare(strict_types=1);

namespace Kettari\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
  /**
   * Finds notification by its name.
   *
   * @param string $name
   * @return object|null
   */
  public function findOneByName(string $name)
  {
    return $this->findOneBy(['name' => $name]);
  }

  /**
   * Finds all notification and orders them in the ascending order.
   *
   * @return array
   */
  public function findAllOrdered()
  {
    return $this->findBy([], ['sortOrder' => 'ASC']);
  }

  /**
   * Finds all default notifications.
   *
   * @return array
   */
  public function findDefault()
  {
    return $this->findBy(['userDefault' => true]);
  }
}
