<?php
declare(strict_types=1);

namespace Kettari\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends EntityRepository
{
  /**
   * Finds notification by its name.
   *
   * @param int $bumpSize
   * @return array
   */
  public function findPending(int $bumpSize = 200)
  {
    return $this->findBy(
      ['status' => 'pending'],
      ['created' => 'ASC'],
      $bumpSize
    );
  }
}
