<?php

namespace Kettari\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
  /**
   * Returns array of roles for anonymous user.
   *
   * @return array
   */
  public function findAnonymous()
  {
    return $this->findBy(['anonymous' => true]);
  }
}
