<?php

namespace Kettari\TelegramBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
  /**
   * Returns array of roles for anonymous user.
   *
   * @return array
   */
  public function findAnonymous()
  {
    return $this->findBy(['anonymous' => true]);
  }

  /**
   * Returns array of roles for anonymous user.
   *
   * @param string $name
   * @return object|null
   */
  public function findOneByName(string $name)
  {
    return $this->findOneBy(['name' => $name]);
  }

  /**
   * Returns non-administrator and non-anonymous roles.
   *
   * @return array
   */
  public function findRegular()
  {
    return $this->findBy(['administrator' => false, 'anonymous' => false]);
  }
}
